# Generated by Django 4.1.3 on 2023-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_product_category_product_subcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
    ]
