# Generated by Django 4.1.3 on 2023-01-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_contact"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contact", new_name="Contact_us",),
    ]
