# Generated by Django 4.1.3 on 2023-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
