# Generated by Django 4.1.3 on 2023-01-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Availability",
            field=models.CharField(
                choices=[("In stock", "In stock"), ("Out of Stock", "Out of Stock")],
                max_length=100,
                null=True,
            ),
        ),
    ]
