# Generated by Django 4.1.3 on 2023-01-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_product_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Condition",
            field=models.CharField(
                choices=[("New", "New"), ("Like New", "Like New"), ("Used", "Used")],
                max_length=100,
                null=True,
            ),
        ),
    ]
